title: A Noobies Blog
author: Bradley Willcott
email: bw-opensource@yahoo.com
description: This is a training blog for me.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  bewillcott

show_excerpts: false # true # set to false to remove excerpts on the homepage
theme: minima
